#Move_group node parameters 
group_name: arm
move_group_timeout: 500 

#Publish tf
publish_tf: true

#Robot setup
end_effector_link: robot_arm_tool0
robot_base_link: robot_base_footprint

#Mongodb
connect_db: false
host: "localhost"
port: 33829


