#Move_group node parameters 
group_name: arm
move_group_timeout: 500 

#Publish tf
publish_tf: true

#Robot setup
end_effector_link: tool0
robot_base_link: base_link

#Mongodb
host: "localhost"
port: 33829


